markdown: kramdown

title: Braja Gopal Patra @ Weill Cornell Medicine

url: '//brajagopalcse.github.io'
production_url: 'https://brajagopalcse.github.io'

permalink: "/news/:year-:month-:day-:title/"

author:
    name: Braja Gopal Patra  
    email: brajagopal.cse@gmail.com
    github: brajagopalcse
    twitter: bgp_tweet
    gravatar: 

#comments:
#    provider: disqusasdf
#    disqus: yannickwurm
#        short_name: "yannickwurm"
#    disqus_name: "adsf"

#analytics:
#    provider: google 
#    google: 
#        tracking_id: 'UA-471841-2'
#        domain: 'wurmlab.github.io'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile']

gems:
  - jekyll-redirect-from
